#!/bin/sh
#  author fengxp
#  time  2016-05-24 
#  program : 配置显示输出，并调用显示

xrandr -s 1920×1080
xrandr -o left
xrandr -q > /root/advStart.log
date >> /root/advStart.log

export LC_ALL="zh_CN.UTF-8"

/var/.eadv/chromStart 

